Implement the versioned.Versioned type with locks.
Joint work with mwhittaker@.

Other changes:
  * Converted babysitter to finer-grained locking, to
    remove the possible lock inversion w.r.t. b.mu.

diff --git a/dev/build_and_test b/dev/build_and_test
--- a/dev/build_and_test
+++ b/dev/build_and_test
@@ -54,7 +54,7 @@ function cmd_vet() {
 
 function cmd_lint() {
   if ! exists golangci-lint; then
-    printf "golangci-lint not found; install via\ngo install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0\n" >&2
+    printf "golangci-lint not found; install via\ngo install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2\n" >&2
     exit 1
   fi
 
