Expose the deployment identifier to the application.
This was a feature requested by one of our users so that they
can distinct between multiple deployments of the same application.

diff --git a/dev/build_and_test b/dev/build_and_test
--- a/dev/build_and_test
+++ b/dev/build_and_test
@@ -54,7 +54,7 @@ function cmd_vet() {
 
 function cmd_lint() {
   if ! exists staticcheck; then
-    printf "staticcheck not found; install via\ngo install honnef.co/go/tools/cmd/staticcheck@v0.4.3\n" >&2
+    printf "staticcheck not found; install via\ngo install honnef.co/go/tools/cmd/staticcheck@v0.4.6\n" >&2
     exit 1
   fi
 
